### ISSUE TITLE
Document Progress

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#648]
We need the progress of the following documents stored in this _private_ folder: https://drive.google.com/open?id=10DuFrxuzbRlqFhuAJ9hkiGnGWGzpSBBU

Please post in progress documents and assets for:

- [x] [Make a Presskit](https://github.com/josefnpat/roguecraft-squadron/issues/86)
- [x] [Presskit of RCS](https://github.com/josefnpat/roguecraft-squadron/issues/623)
- [x] [Presskit of MSS](https://github.com/josefnpat/roguecraft-squadron/issues/622)
- [x] [Prepare Platform Release](https://github.com/josefnpat/roguecraft-squadron/issues/558)
- [x] [Update Website Contents](https://github.com/josefnpat/roguecraft-squadron/issues/335)
- [x] [Recreate demo video](https://github.com/josefnpat/roguecraft-squadron/issues/312)

We need the demo video assets for tomorrow please.
