### ISSUE TITLE
Make tickets from NAGN notes

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#795]
Issues:

- [ ] People struggled to choose the correct ship to build
- [ ] People didn't see or understand blue line
- [ ] The queue needs to be better explained
- [ ] Text is hard to read
- [ ] Players don't see build section
- [x] Players don't see what to click on in Research #797
- [x] Tip has no guide arrow
- [ ] Enemies are hard to see (Consider choosing higher contrast background)
- [ ] No radius for gathering
- [ ] Radius is hard to see
- [ ] People are having problems telling the difference between civilian and military ships
- [x] Change hue on station in tutorial to avoid confusion with enemy #798
- [x] need arrow on tutorial #802

Feature requests:

- [ ] Add ships with multi purpose
- [ ] Waypoint queuing
- [ ] Players don't realize material is full
- [ ] Turrets are too strong
- [ ] Choose where turrets are built
